version: 0.2

phases:
    install:
        runtime-versions:
          nodejs: 10
        commands:
            - curl -s -o mime.types "https://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co"
            - sudo mv mime.types /etc/
            - npm ci
    build:
        commands:
            - npm run build && aws s3 sync public "s3://preview.dbanks.design/$(echo $CODEBUILD_WEBHOOK_TRIGGER | tr / -)" --delete --acl public-read

cache:
    paths:
        - node_modules/**/*
        - public/**/*
        - /usr/local/lib/node_modules/**/*